In [6]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [7]:
#chisquare test
data=sns.load_dataset("tips")

In [8]:
data[['sex','smoker']]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [9]:
#summirzaion of the data using crosstab
datatable=pd.crosstab(data['sex'],data['smoker'])

In [10]:
obeserved_value=datatable.values

In [11]:
obeserved_value

array([[60, 97],
       [33, 54]])

In [12]:
datatable

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [15]:
import scipy.stats as stats
stats,pvalue,dof,expected_value=stats.chi2_contingency(obeserved_value)


In [16]:
expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [17]:
#using chisquare critical value
dof=1


In [18]:
from scipy.stats import chi2


In [19]:
for i in zip(obeserved_value,expected_value):
    print(i)

(array([60, 97]), array([59.84016393, 97.15983607]))
(array([33, 54]), array([33.15983607, 53.84016393]))


In [26]:
chisquare=sum([(o - e) ** 2 / e for o, e in zip(obeserved_value, expected_value)])

In [28]:
chisquare=chisquare[0]+chisquare[1]

In [29]:
chisquare

np.float64(0.001934818536627623)

In [30]:
dof

1

In [31]:
alpha=0.05

In [36]:
chicrital=chisquare.ppf(1-alpha,dof)

AttributeError: 'numpy.float64' object has no attribute 'ppf'