In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,3,(2,3))

In [3]:
arr

array([[2, 1, 1],
       [1, 1, 1]], dtype=int32)

In [5]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))


In [6]:
arr1

array([[2, 1, 1],
       [2, 2, 1],
       [2, 2, 2]], dtype=int32)

In [7]:
arr2

array([[2, 1, 1],
       [2, 1, 1],
       [1, 1, 2]], dtype=int32)

In [8]:
arr.flatten() #return a copy of the array to colapsed in iinto the one dimension


array([1, 1, 2, 2, 2, 2, 2, 2, 1], dtype=int32)

In [9]:
#expand dimension
arr=np.array([1,2,3,4,5])

In [21]:
np.expand_dims(arr,axis=0)

array([[1, 2, 3, 4, 5]])

In [14]:
arr.ndim

1

In [23]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [24]:
arr=np.zeros((3,4))

In [25]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [29]:
a=np.array([[1,2],[3,4],[5,6]])

In [30]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
#Squeezzing the dimension
arr=np.squeeze(a) #Remove axes the length one from a

In [38]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6])

In [43]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [5, 6],
       [5, 6]])

In [44]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
np.repeat(a,3,axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4],
       [5, 5, 5, 6, 6, 6]])

In [47]:
np.roll(a,-1)

array([[2, 3],
       [4, 5],
       [6, 1]])

In [49]:
a=np.array([[1],[2],[3]])

In [53]:
np.roll(a,-1)

array([[2],
       [3],
       [1]])

In [52]:
a

array([[1],
       [2],
       [3]])

In [54]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
np.roll(arr,-1)

array([[2, 3],
       [4, 5],
       [6, 1]])

In [56]:
#operation on the numpy sting array
d=np.array(["Maava","skill","frontend"])


In [57]:
d

array(['Maava', 'skill', 'frontend'], dtype='<U8')

In [60]:
np.char.upper(d)

array(['MAAVA', 'SKILL', 'FRONTEND'], dtype='<U8')

In [61]:
np.char.capitalize(d)

array(['Maava', 'Skill', 'Frontend'], dtype='<U8')

In [62]:
#Matematical function
np.sin(a)


array([[0.84147098],
       [0.90929743],
       [0.14112001]])

In [63]:
np.cos(a)

array([[ 0.54030231],
       [-0.41614684],
       [-0.9899925 ]])

In [64]:
np.exp(a)

array([[ 2.71828183],
       [ 7.3890561 ],
       [20.08553692]])

In [65]:
np.power(a,3)

array([[ 1],
       [ 8],
       [27]])

In [66]:
np.max(a)

np.int64(3)

In [67]:
np.mean(a)

np.float64(2.0)

In [68]:
np.min(a)

np.int64(1)

In [69]:
np.std(a)

np.float64(0.816496580927726)