In [1]:
#DATA TOOLKIT
#Numpy
#Pandas
#Matplotlib
#Seaborn
#Plotly
#Bokeh


In [2]:
#Data sccience ->Processfollow->CRISP-DN Farmework(CroSS INdustry process For the data mining)
#Data Minnig ->getting inside from the data 
#Bussiness Understanding 
    #to prdict the house of the 
        #Depend on the area of the house
        #No of room
#Dsta Understanding
    #How area of house decide the price of the house
        #Area of the house incresing the price of the house also increasing
        #No of room increasing the the price is also increasing                         #Through Exploratory Data Analysis
        #No of increasing then Area is also incresing
#Data Prepration
#Modelling
#Evalution of the model 
#Deployment



In [3]:
#Library -->A library is a collection of pre-write code ,that is used to perform common task
#basic Cal,Calculus,Linear Alegra -->to form Module -->all this kept together to is called Pakaage
#Multiple Package together is called as library


In [4]:
#Libray xontain together lots of package and modouls


In [5]:
#Numpy stands for the numeric Python
#Developed by 2005 

In [8]:
import numpy as np
np.__version__

'2.0.2'

In [9]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [10]:
lis=[1,2,3,"Manab"]

In [11]:
#Numpy stores the data in the numpy array
#An array is an container/data structure used to store data  of same datatype 

In [12]:
#Why numpy? alredy we have list, c++ is the most fastest programmming languge
#Numpy is buit in c >> therefore the numpy computation is very very fast
#due to array since it always store homogeneous data, numpy array is faster
#since it store homogeneuos data >> it has continous memory allocation
#Mathmetical computaion is fast


In [13]:
l=[1,2,3,4,5]
arr=np.array(l)

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
l=[1,2,3,4,5,"Manav"]
arr=np.array(l)

In [16]:
arr

array(['1', '2', '3', '4', '5', 'Manav'], dtype='<U21')

In [17]:
#array store homogenous data 
l=[1,2,3,4,5,3.4]
arr=np.array(l)

In [18]:
arr

array([1. , 2. , 3. , 4. , 5. , 3.4])

In [20]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim #arr has only rows

1

In [23]:
arr1=np.array([[1,2,3],[4,5,6]])

In [24]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr1.ndim

2

In [26]:
np.matrix([1,2,3,4]) #Matrix is the specialized two dimension array of 2 dimension


matrix([[1, 2, 3, 4]])

In [27]:
#To understand the dimension,see the bracket


In [30]:
#More way to convert the array
l=[1,2,3,4]
np.asarray(l)#initial func  asarray to convert to an array ,after that np.arra came


array([1, 2, 3, 4])

In [31]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [32]:
#asany array 
t=([1,2,3,4],[4,5,6,7])
type(t)


tuple

In [33]:
np.array(t)

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [35]:
arr[0]

np.float64(1.0)

In [36]:
arr[0]=100
arr

array([100. ,   2. ,   3. ,   4. ,   5. ,   3.4])

In [38]:
a=arr #This will point to the same memory location, so if their is change any array so it willl reflect it both
#it will reflect form both

In [39]:
a[0]=1

In [40]:
arr

array([1. , 2. , 3. , 4. , 5. , 3.4])

In [45]:
#shallow copy >>change in the one array will be change in the other
a[0]=122

In [42]:
b=arr.copy()
#deep copy 

In [46]:
b[0]=1111

In [47]:
arr

array([122. ,   2. ,   3. ,   4. ,   5. ,   3.4])

In [48]:
b

array([1111. ,    2. ,    3. ,    4. ,    5. ,    3.4])

In [53]:
#to create array>>np.array,np.asarray,np.asany array
#Multiple approch to gentrate an array
arr1=np.fromfunction(lambda i,j:i==j ,(3,3))

In [54]:
arr1.ndim


2

In [55]:
arr1.shape

(3, 3)

In [57]:
arr1.size

9

In [59]:
np.fromfunction(lambda i,j:i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [61]:
iterable=(i for i in range(5))



In [63]:
np.fromiter(iterable,int)

array([0, 1, 2, 3, 4])

In [65]:
np.fromstring('22 23 24',sep=" ",dtype=int)

array([22, 23, 24])

In [67]:
#for string character you have to use split
string ="Manav,Ajay,bijay" 
string.split(",")

['Manav', 'Ajay', 'bijay']

In [68]:
np.array(string.split(","))

array(['Manav', 'Ajay', 'bijay'], dtype='<U5')

In [69]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
#another method of numpy to genrate the squence of the number
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [72]:
np.linspace(1,5,10) #give me 10 number 0 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])