In [1]:
import numpy as np 

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
#3 dimensional 
a=np.zeros((3,2,3))

In [13]:
a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
a.ndim

3

In [35]:
arr=np.zeros((2,3))

In [36]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
arr+5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [38]:
brr=np.eye(3,3)

In [39]:
brr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
brr=np.eye(3,3 ,dtype=int)

In [41]:
brr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [44]:
crr=np.empty((2,4))# random intialize the value

In [45]:
crr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
#Optinal>> Random module heip us 
import random
random.choice((1,2,3,4,5))

4

In [50]:
random.choice(("Ajay"))

'y'

In [52]:
random.randrange(1,10)

6

In [53]:
random.random()#a random number btw the 0(include) and 1(exclude)


0.997943241686344

In [54]:
lis=[1,2,34,4]
random.shuffle(lis)

In [55]:
lis

[34, 4, 1, 2]

In [57]:
random.uniform(7,14)

8.74511946712925

In [58]:
#random number related concept in the numpy
np.array([])

array([], dtype=float64)

In [ ]:
np.random.random_sample((5,))#1 dim array of 5 random no 

array([0.60913766, 0.33041985, 0.36275839, 0.90854456, 0.98754054])

In [63]:
np.random.rand(1)

array([0.40947827])

In [64]:
np.random.rand(2,3)

array([[0.19080415, 0.97742187, 0.97581254],
       [0.92857632, 0.81856322, 0.08192348]])

In [65]:
np.random.randn(2,3)

array([[ 0.53846899,  1.21312858, -0.71270873],
       [-0.67455691, -0.16950903, -0.2415464 ]])

In [68]:
a=np.random.randint(1,5,size=(3,4))#start from 1 and end 4-1 

In [69]:
a

array([[4, 1, 4, 1],
       [4, 4, 3, 3],
       [1, 1, 1, 4]], dtype=int32)

In [70]:
a.ndim

2

In [71]:
a.shape

(3, 4)

In [72]:
a.size

12

In [73]:
#reshaping of the array
a.reshape(2,6)#Returning the array containnig the same data with a new shape

array([[4, 1, 4, 1, 4, 4],
       [3, 3, 1, 1, 1, 4]], dtype=int32)

In [74]:
#array size will never change ,always reshape shape parameter should be the multiplication of the orignal array size

In [78]:
#case when you dont know in reshape what should be the row or column count
a.reshape(4,-1)

array([[4, 1, 4],
       [1, 4, 4],
       [3, 3, 1],
       [1, 1, 4]], dtype=int32)

In [79]:
a.reshape(12,1).base

array([[4, 1, 4, 1],
       [4, 4, 3, 3],
       [1, 1, 1, 4]], dtype=int32)

In [82]:
a.reshape(2,2,3)#it shpuld be the multiple 4 time in the third dimension

array([[[4, 1, 4],
        [1, 4, 4]],

       [[3, 3, 1],
        [1, 1, 4]]], dtype=int32)

In [84]:
#condition on the array
a=np.random.randint(1,10,(5,6))

In [85]:
a

array([[7, 9, 9, 4, 2, 5],
       [5, 2, 5, 7, 4, 6],
       [7, 7, 4, 8, 2, 1],
       [5, 3, 6, 2, 8, 2],
       [6, 6, 2, 8, 4, 6]], dtype=int32)

In [86]:
a>3

array([[ True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [ True, False,  True, False,  True, False],
       [ True,  True, False,  True,  True,  True]])

In [89]:
a[(a>3)]

array([7, 9, 9, 4, 5, 5, 5, 7, 4, 6, 7, 7, 4, 8, 5, 6, 8, 6, 6, 8, 4, 6],
      dtype=int32)

In [90]:
#to aceess the element in the array


In [92]:
a[0]

array([7, 9, 9, 4, 2, 5], dtype=int32)

In [94]:
a[0][3]

np.int32(4)

In [95]:
a[0:3]

array([[7, 9, 9, 4, 2, 5],
       [5, 2, 5, 7, 4, 6],
       [7, 7, 4, 8, 2, 1]], dtype=int32)

In [97]:
a[0:3,[0,2]]

array([[7, 9],
       [5, 5],
       [7, 4]], dtype=int32)

In [98]:
#slicing on row and col together
a

array([[7, 9, 9, 4, 2, 5],
       [5, 2, 5, 7, 4, 6],
       [7, 7, 4, 8, 2, 1],
       [5, 3, 6, 2, 8, 2],
       [6, 6, 2, 8, 4, 6]], dtype=int32)

In [101]:
a[0:3,1:4]

array([[9, 9, 4],
       [2, 5, 7],
       [7, 4, 8]], dtype=int32)

In [102]:
a[0,[1,3]]

array([9, 4], dtype=int32)

In [103]:
a[0:4,0:3]

array([[7, 9, 9],
       [5, 2, 5],
       [7, 7, 4],
       [5, 3, 6]], dtype=int32)

In [109]:
#mathematical operation on two array
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))


In [110]:
arr1

array([[2, 1, 1],
       [2, 2, 1],
       [1, 2, 1]], dtype=int32)

In [111]:
arr2

array([[1, 2, 1],
       [1, 2, 2],
       [2, 2, 1]], dtype=int32)

In [113]:
arr1+arr2#index wise element addition

array([[3, 3, 2],
       [3, 4, 3],
       [3, 4, 2]], dtype=int32)

In [114]:
arr1-arr2

array([[ 1, -1,  0],
       [ 1,  0, -1],
       [-1,  0,  0]], dtype=int32)

In [115]:
arr1*arr2

array([[2, 2, 1],
       [2, 4, 2],
       [2, 4, 1]], dtype=int32)

In [116]:
arr1/arr2

array([[2. , 0.5, 1. ],
       [2. , 1. , 0.5],
       [0.5, 1. , 1. ]])

In [117]:
arr1/0

C:\Users\91983\AppData\Local\Temp\ipykernel_2496\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [118]:
#Matrix Multiplication
arr1@arr2

array([[ 5,  8,  5],
       [ 6, 10,  7],
       [ 5,  8,  6]], dtype=int32)

In [119]:
np.dot(arr1,arr2)

array([[ 5,  8,  5],
       [ 6, 10,  7],
       [ 5,  8,  6]], dtype=int32)

In [127]:
#broadcasting
arr=np.zeros((3,4))

In [128]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [129]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [130]:
a=np.array([1,2,3,4])

In [131]:
a

array([1, 2, 3, 4])

In [133]:
arr=arr+a

In [134]:
arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [135]:
#Transpose
arr.T

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])